# Generated by Django 5.1.3 on 2024-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='header',
            field=models.CharField(max_length=255),
        ),
    ]
